### ISSUE TITLE
Document start token (---) causes pureyaml to fail

### ISSUE THREAD

**Issue by schwa** [bionikspoon/pureyaml#7]
The following correct YAML (run against other yaml parsers) causes pureyaml to file

``` yaml

---
:bucket_name: ZZZZ
:aws_s3_client_options:
  :region: us-east-1
  :access_key_id: XXXX
  :secret_access_key: YYYY

```

Exception:

```
Traceback (most recent call last):
  File "/Users/schwa/Projects/punic/punic/carthage_cache.py", line 21, in __init__
    d = pureyaml.load(Path('.carthage_cache.yml').open())
  File "/usr/local/lib/python2.7/site-packages/pureyaml/__init__.py", line 47, in load
    return loads(s.read(), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pureyaml/__init__.py", line 55, in loads
    return cls(**kwargs).decode(s)
  File "/usr/local/lib/python2.7/site-packages/pureyaml/decoder.py", line 13, in decode
    return self.visit(YAMLParser().parse(s))
  File "/usr/local/lib/python2.7/site-packages/pureyaml/parser.py", line 58, in parse
    return self.parser.parse(data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python2.7/site-packages/pureyaml/parser.py", line 77, in p_error
    raise YAMLSyntaxError(p)
pureyaml.exceptions.YAMLSyntaxError: unexpected: LexToken(DOC_START,u'---',1,0)

'---\n:bucket_name: ZZZZ\n:aws_s3_client_options:\n  :region: us-east-1\n  :access_key_id: XXXX\n  :secret_access_key: YYYY\n\n
^^^^
```

**Comment by bitbier** [comment]
I'm not a maintainer of this project, but this actually works. You may want to update to the latest version if you haven't already and verify, but for instance:

```
>>> test = """
... ---
... :bucket_name: ZZZZ
... :aws_s3_client_options:
...   :region: us-east-1
...   :access_key_id: XXXX
...   :secret_access_key: YYYY
... """
>>> pureyaml.loads(test)
WARNING: yacc table file version is out of date
Generating LALR tables
WARNING: 15 shift/reduce conflicts
WARNING: 1 reduce/reduce conflict
WARNING: reduce/reduce conflict in state 30 resolved using rule (scalar -> SCALAR)
WARNING: rejected rule (scalar_group -> SCALAR) in state 30
{':bucket_name': 'ZZZZ', ':aws_s3_client_options': {':region': 'us-east-1', ':access_key_id': 'XXXX', ':secret_access_key': 'YYYY'}}
```

**Comment by bitbier** [comment]
It looks like somehow you may have an extra character `'` in your string proceeding `---`
